# Generated by Django 4.1.4 on 2023-07-11 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstAndLastName', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other')], default='Other', max_length=200)),
                ('yearsProfessionalExperince', models.IntegerField(default=5)),
                ('yearsofBusinessEducationExperince', models.IntegerField(default=5)),
                ('jobTitle', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('foodTruckName', models.CharField(max_length=200)),
                ('quality', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('capacity', models.IntegerField(default=100)),
                ('price', models.IntegerField(default=10)),
                ('priceStrat', models.FloatField(default=0.5)),
                ('onlineMarketing', models.FloatField(default=0.1)),
                ('printMarketing', models.FloatField(default=0.1)),
                ('wordOfMouthMarketing', models.FloatField(default=0.1)),
                ('foodType', models.CharField(choices=[('Comfort Food', 'Comfort Food'), ('Italian', 'Italian'), ('Asian', 'Asian'), ('Dessert', 'Dessert'), ('Smoothie', 'Smoothie')], default='Comfort Food', max_length=200)),
                ('mission', models.CharField(max_length=2000)),
                ('vision', models.CharField(max_length=2000)),
                ('values', models.CharField(max_length=2000)),
                ('cashBalance', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Scenerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(default='description', max_length=2000)),
                ('max_rounds', models.IntegerField(default=10)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('weather', models.DecimalField(decimal_places=2, default=0.5, max_digits=100)),
                ('turnout_chance', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('round_number', models.IntegerField(default=1)),
                ('sales', models.FloatField(default=0)),
                ('ingredient_cost', models.FloatField(default=0)),
                ('comission_cost', models.FloatField(default=0)),
                ('total_varriable_cost', models.FloatField(default=0)),
                ('gm', models.FloatField(default=0)),
                ('salaries', models.FloatField(default=0)),
                ('loan_payments', models.FloatField(default=0)),
                ('event_payments', models.FloatField(default=0)),
                ('marketing_spend', models.FloatField(default=0)),
                ('total_fixed_costs', models.FloatField(default=0)),
                ('net_income', models.FloatField(default=0)),
                ('tax_expense', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_business', to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_scenerio', to='game.scenerio')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.IntegerField(default=10000)),
                ('description', models.CharField(max_length=2000)),
                ('priceSensitivity', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('qualitySensitivity', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('onlineMarketingSensitivity', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('printMarketingSensitivity', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('wordOfMouthMarketingSensitivity', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('weatherSensitivity', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('comfortFoodPreference', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('italianFoodPreference', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('asianFoodPreference', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('dessertPreference', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('smoothieFoodPreference', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('master', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_segment_scenerio', to='game.scenerio')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('marketing_type', models.CharField(choices=[('Online', 'Online'), ('Print', 'Print'), ('Word of Mouth', 'Word of Mouth')], default='Online', max_length=200)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.business')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=10000.0)),
                ('intrest', models.FloatField(default=0.08)),
                ('master', models.BooleanField(default=True)),
                ('how_many_months', models.FloatField(default=36)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_scenerio', to='game.scenerio')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.FloatField(default=1.5)),
                ('qualityBonus', models.DecimalField(decimal_places=2, default=0.03, max_digits=100)),
                ('capacityCost', models.FloatField(default=0.33)),
                ('master', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_scenerio', to='game.scenerio')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=10000, max_digits=100)),
                ('description', models.CharField(max_length=2000)),
                ('capacityBonus', models.IntegerField(default=1000)),
                ('qualityBonus', models.DecimalField(decimal_places=2, default=0.1, max_digits=3)),
                ('master', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_truck_scenerio', to='game.scenerio')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('salary', models.IntegerField(default=10000)),
                ('comission', models.DecimalField(decimal_places=2, default=0.03, max_digits=100)),
                ('capacityBonus', models.IntegerField(default=1000)),
                ('qualityBonus', models.DecimalField(decimal_places=2, default=0.03, max_digits=100)),
                ('master', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_scenerio', to='game.scenerio')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='scenerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_truck_bus_scenerio', to='game.scenerio'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
