# Generated by Django 4.1.4 on 2023-07-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_round_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=2000)),
                ('weather', models.DecimalField(decimal_places=2, default=0.5, max_digits=100)),
                ('turnout_chance', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
                ('round_number', models.IntegerField(default=1)),
                ('sales', models.FloatField(default=0)),
                ('ingredient_cost', models.FloatField(default=0)),
                ('comission_cost', models.FloatField(default=0)),
                ('total_varriable_cost', models.FloatField(default=0)),
                ('gm', models.FloatField(default=0)),
                ('salaries', models.FloatField(default=0)),
                ('loan_payments', models.FloatField(default=0)),
                ('event_payments', models.FloatField(default=0)),
                ('marketing_spend', models.FloatField(default=0)),
                ('total_fixed_costs', models.FloatField(default=0)),
                ('net_income', models.FloatField(default=0)),
                ('tax_expense', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roundnew_business', to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roundnew_scenerio', to='game.scenerio')),
            ],
        ),
    ]
