# Generated by Django 4.1.4 on 2023-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_roundnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundnew',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
