# Generated by Django 4.1.4 on 2023-07-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_roundnew_revenue_delete_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='quality',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comission',
            field=models.FloatField(default=0.03),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualityBonus',
            field=models.FloatField(default=0.03),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='qualityBonus',
            field=models.FloatField(default=0.03),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='qualityBonus',
            field=models.FloatField(default=0.03),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='asianFoodPreference',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='comfortFoodPreference',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='dessertPreference',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='italianFoodPreference',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='onlineMarketingSensitivity',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='priceSensitivity',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='printMarketingSensitivity',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='qualitySensitivity',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='smoothieFoodPreference',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='weatherSensitivity',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='marketsegment',
            name='wordOfMouthMarketingSensitivity',
            field=models.FloatField(default=0.1),
        ),
    ]
