# Generated by Django 4.1.4 on 2023-07-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_business_quality_alter_employee_comission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundnew',
            old_name='total_fixed_costs',
            new_name='total_fixed_cost',
        ),
    ]
