# Generated by Django 4.1.4 on 2023-07-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_total_fixed_costs_roundnew_total_fixed_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment',
            field=models.FloatField(default=0),
        ),
    ]
