# Generated by Django 4.1.4 on 2023-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_loan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='vcOwnership',
            field=models.FloatField(default=0.0),
        ),
    ]
