# Generated by Django 4.1.4 on 2023-07-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_business_vcownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.FloatField(default=0)),
                ('liabilities', models.FloatField(default=0)),
                ('owners_equity', models.FloatField(default=0)),
                ('vc_cut', models.FloatField(default=0)),
                ('final_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_business', to='game.business')),
                ('scenerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_scenerio', to='game.scenerio')),
            ],
        ),
    ]
