# Generated by Django 4.1.4 on 2023-07-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
