# Generated by Django 4.1.4 on 2023-07-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_report_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='final_score',
            field=models.FloatField(default=0),
        ),
    ]
