# Generated by Django 4.1.4 on 2023-07-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_loan_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
