# Generated by Django 4.1.4 on 2023-07-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_report_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='summarize_your_strategy',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
