# Generated by Django 4.1.4 on 2023-07-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_business_summarize_your_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='firstAndLastName',
            field=models.CharField(max_length=200, verbose_name='First and Last Name'),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(max_length=200, verbose_name='Current Industry?'),
        ),
        migrations.AlterField(
            model_name='business',
            name='jobTitle',
            field=models.CharField(max_length=200, verbose_name='Current Job Title?'),
        ),
        migrations.AlterField(
            model_name='business',
            name='yearsProfessionalExperince',
            field=models.IntegerField(default=5, verbose_name='How many years of Professional Experince in your field?'),
        ),
        migrations.AlterField(
            model_name='business',
            name='yearsofBusinessEducationExperince',
            field=models.IntegerField(default=5, verbose_name='How many years of Formal Business Education?'),
        ),
    ]
