# Generated by Django 4.1.4 on 2023-07-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_business_firstandlastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='firstAndLastName',
            field=models.CharField(max_length=200, verbose_name='First and Last Name?'),
        ),
    ]
