# Generated by Django 4.1.4 on 2023-07-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_business_firstandlastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('risk', models.FloatField(default=0)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_business', to='game.business')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_log', to='game.business')),
            ],
        ),
    ]
