# Generated by Django 4.1.4 on 2023-07-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='LogEntry',
        ),
    ]
