# Generated by Django 4.1.4 on 2023-07-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_rename_log_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='current_round',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='round',
            field=models.FloatField(default=0),
        ),
    ]
