# Generated by Django 4.1.4 on 2023-08-12 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_business_current_round_alter_logentry_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='yearsProfessionalExperince',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='How many years of Professional Experince in your field?'),
        ),
        migrations.AlterField(
            model_name='business',
            name='yearsofBusinessEducationExperince',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='How many years of Formal Business Education?'),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
