# Generated by Django 4.1.4 on 2023-08-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_remove_business_current_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='current_round',
            field=models.FloatField(default=0),
        ),
    ]
