# Generated by Django 4.1.4 on 2023-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_business_current_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2000)),
                ('last_name', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
                ('master', models.BooleanField(default=False)),
            ],
        ),
    ]
