# Generated by Django 4.1.4 on 2023-09-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_consentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsentForm',
            new_name='Consent',
        ),
    ]
