# Generated by Django 4.1.4 on 2023-09-30 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_rename_consentform_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=100),
        ),
    ]
