# Generated by Django 4.1.4 on 2023-10-23 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_business_price_alter_foodtruck_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='yearsProfessionalExperince',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='How many years of Professional Experince in your field?'),
        ),
        migrations.AlterField(
            model_name='business',
            name='yearsofBusinessEducationExperince',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='How many years of Formal Business Education?'),
        ),
    ]
